---
# SPDX-License-Identifier: MIT
#
# Setup www.
#
- name: Setup www
  hosts: www
  gather_facts: false
  tasks:
    - name: Ensure required packages are installed
      package:
        name: httpd
        state: present

    - name: Ensure www server is started
      service:
        name: httpd
        state: started

    - name: Ensure www contents exist
      copy:
        content: |
          <html>
            <head><title>Hello world!</head>
            <body><h1>Hello world!</h1></body>
          </html>
        dest: /var/www/html/hello.html
        mode: 0644
        seuser: system_u
        serole: object_r
        setype: httpd_system_content_t

    - name: Test everything works
      uri:
        url: http://localhost/hello.html
