---
# SPDX-License-Identifier: MIT
#
# Setup www.
#
- name: Setup www
  hosts: www
  gather_facts: false
  tasks:
    - name: Ensure required packages are installed
      package:
        name: httpd
        state: present

    # workaround to let systemd knows about this new service.
    #
    # :seealso:
    # https://github.com/ansible/ansible/issues/36585#issuecomment-441300410
    - name: Ensure this new service is registered
      command: |
        systemctl daemon-reload
      changed_when: false
      tags:
        - skip_ansible_lint

    - name: Ensure www contents exist
      copy:
        content: |
          <html>
            <head><title>Hello world!</head>
            <body><h1>Hello world!</h1></body>
          </html>
        dest: /var/www/html/hello.html
        mode: 0644
        # seuser: system_u
        # serole: object_r
        # setype: httpd_system_content_t

    - name: Ensure www server is started
      service:
        name: httpd
        state: started

    - name: Test everything works
      uri:
        url: http://localhost/hello.html
