---
# SPDX-License-Identifier: MIT
#
# Setup www.
#
- name: Setup www
  hosts: www
  gather_facts: true
  become: true
  roles:
    - github.ssato.simple-httpd-example
    - name: github.ssato.simple-httpd-example
      vars:
        sshe_verification_mode: true
